# Disable Eureka client registration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Eureka instance hostname
eureka.instance.prefer-ip-address=true

# Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
